from typing import Protocol


class CursorInterfaceType(Protocol):
    def execute(self) -> None: ...
    def executemany(self) -> None: ...
    def close(self) -> None: ...
    def fetchone(self) -> None: ...
    def fetchmany(self) -> None: ...
    def fetchall(self) -> None: ...
